### ISSUE TITLE
eth deposit generated address secret key

### ISSUE THREAD

**Issue by lekabyte** [openware/opendax#146]
How is secret key generated or how do you decode it so that you have access to ETH once you deposit?

I created blockchain, wallets, currencie and opendax created user dopist address for me. I deposited small amount of ETH without problem. Now that I want to test withdraw I can't do it because there is non ETH on hotwallet address. So i tried using same hotwallet address as opendax generated for client deposit. But i don't know the secret passcode. I looked into db and found out that is encrypt:

 secret_encrypted: `CTSISwUCn1gwNayGtWJX/DBQtzIcS9WEvgWti76377vFZ0g/ZZW04IrPFITA0UU2zPOXKYD0jAt417L29zgHNGR67fGhLKKBIVRdgupfyuc=`

How can I decode this. Or how do I get access to client deposits?

**Comment by lekabyte** [comment]
ok so i figure it out. it's collected to hot wallet after deposit. buy you must have some eth to pay for collection in hot wallet before client make deposit. i did manual collection and from logs i can see:

`{"level":"WARN","time":"2020-05-14 12:29:45","message":"The API accepted deposit collection and assigned transaction ID: [{\"to_address\"=>\"0x9f164af5275b0099552e85eb5138948daa3d6a6a\", \"amount\"=>\"0.006\", \"currency_id\"=>\"eth\", \"status\"=>\"pending\", \"hash\"=>\"0x76696a37fab01104769ea3a99e2ec517a56a236ad7bf6b8a6bf8bc0345d73640\"}]."}`

but collection never happened. https://etherscan.io/tx/0x76696a37fab01104769ea3a99e2ec517a56a236ad7bf6b8a6bf8bc0345d73640 does not exist...

**Comment by lekabyte** [comment]
Withdraw:

```
{"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"message":"Received request for processing withdraw.","level":"WARN","time":"2020-05-14 12:35:46"}
withdraw_coin_1            | {"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"amount":"0.0051","fee":"0.001","currency":"ETH","rid":"0x9f164af5275b0099552e85eb5138948daa3d6a6a","message":"Sending witdraw.","level":"WARN","time":"2020-05-14 12:35:46"}
withdraw_coin_1            | {"level":"WARN","time":"2020-05-14 12:35:46","message":"[vault-rails] Using in-memory cipher - this is not secure and should never be used in production-like environments!"}
withdraw_coin_1            | {"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"message":"Sending request to Wallet Service.","level":"WARN","time":"2020-05-14 12:35:46"}
withdraw_coin_1            | {"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"tid":"0x4aae9be8e6a9b5bac3c8c3c13f0edde23c872f2c8abadfb0aeee2e3ac5ebca85","message":"The currency API accepted withdraw and assigned transaction ID.","level":"WARN","time":"2020-05-14 12:35:51"}
withdraw_coin_1            | {"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"message":"Updating withdraw state in database.","level":"WARN","time":"2020-05-14 12:35:51"}
withdraw_coin_1            | {"worker":"/home/app/app/workers/amqp/withdraw_coin.rb","id":4,"message":"Withdrawal has processed","level":"WARN","time":"2020-05-14 12:35:51"}
```

transaction does not exist... https://etherscan.io/tx/0x4aae9be8e6a9b5bac3c8c3c13f0edde23c872f2c8abadfb0aeee2e3ac5ebca85

**Comment by lekabyte** [comment]
is it possible that transaction is too small?

i tried sending transaction from command line

`curl --data '{"method":"personal_sendTransaction","params":[{"from":"0x9f164af5275b0099552e85eb5138948daa3d6a6a","to":"0x9b37592f7aa0ea113876ee1bd699deb09f1d2057","value":"0x38D7EA4C68000"},"XXXXXX(password)"],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545`

`{"jsonrpc":"2.0","error":{"code":-32010,"message":"Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 81000000000000000 and got: 5100560000000000."},"id":1}`

value: 38D7EA4C68000 = 0.001
0x9f164af5275b0099552e85eb5138948daa3d6a6a balance: 0.00510056

i think the deposit, collection and withdraw numbers are to small to process.

**Comment by counos** [comment]
> ok so i figure it out. it's collected to hot wallet after deposit. buy you must have some eth to pay for collection in hot wallet before client make deposit. i did manual collection and from logs i can see:
> 
> `{"level":"WARN","time":"2020-05-14 12:29:45","message":"The API accepted deposit collection and assigned transaction ID: [{\"to_address\"=>\"0x9f164af5275b0099552e85eb5138948daa3d6a6a\", \"amount\"=>\"0.006\", \"currency_id\"=>\"eth\", \"status\"=>\"pending\", \"hash\"=>\"0x76696a37fab01104769ea3a99e2ec517a56a236ad7bf6b8a6bf8bc0345d73640\"}]."}`
> 
> but collection never happened. https://etherscan.io/tx/0x76696a37fab01104769ea3a99e2ec517a56a236ad7bf6b8a6bf8bc0345d73640 does not exist...

How do you manually collect  ?

**Comment by gelinger777** [comment]
```blockchain_1            | {"level":"ERROR","time":"2022-01-19 23:36:34","message":"/home/app/lib/peatio/ethereum/blockchain.rb:49:in `fetch'\n/home/app/lib/peatio/ethereum/blockchain.rb:49:in `block (2 levels) in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `each'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `find'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `block in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `each'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `each_with_object'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `fetch_block!'\n/home/app/app/services/blockchain_service.rb:49:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:38:in `block (3 levels) in start'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:36:in `block (2 levels) in start'\n/home/app/app/workers/daemons/blockchain.rb:22:in `loop'\n/home/app/app/workers/daemons/blockchain.rb:22:in `block in start'"}
blockchain_1            | {"level":"WARN","time":"2022-01-19 23:36:34","message":"Error: key not found: \"to\". Sleeping for 10 seconds"}
blockchain_1            | {"level":"WARN","time":"2022-01-19 23:36:44","message":"The runner for eth-testnet is up to date (2022-01-19 23:20:55 >= 2022-01-19 23:20:55)"}
blockchain_1            | {"level":"ERROR","time":"2022-01-19 23:36:44","message":"#<KeyError: key not found: \"to\">"}
blockchain_1            | {"level":"ERROR","time":"2022-01-19 23:36:44","message":"/home/app/lib/peatio/ethereum/blockchain.rb:49:in `fetch'\n/home/app/lib/peatio/ethereum/blockchain.rb:49:in `block (2 levels) in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `each'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `find'\n/home/app/lib/peatio/ethereum/blockchain.rb:47:in `block in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `each'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `each_with_object'\n/home/app/lib/peatio/ethereum/blockchain.rb:43:in `fetch_block!'\n/home/app/app/services/blockchain_service.rb:49:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:38:in `block (3 levels) in start'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:36:in `block (2 levels) in start'\n/home/app/app/workers/daemons/blockchain.rb:22:in `loop'\n/home/app/app/workers/daemons/blockchain.rb:22:in `block in start'"}
blockchain_1            | {"level":"WARN","time":"2022-01-19 23:36:44","message":"Error: key not found: \"to\". Sleeping for 10 seconds"}
