### ISSUE TITLE
ETH collection is skipped every time.

### ISSUE THREAD

**Issue by alxtrade** [openware/opendax#164]
ETH collection does not work. Docker logs for peatio deposit_collection:

 {"level":"ERROR","time":"2020-06-16 21:17:31","message":"Failed to collect fee transfer deposit 7. See exception details below."}
{"level":"ERROR","time":"2020-06-16 21:17:31","message":"#<Ethereum::Blockchain::UndefinedCurrencyError: Ethereum::Blockchain::UndefinedCurrencyError>"}
{"level":"ERROR","time":"2020-06-16 21:17:31","message":"/home/app/lib/peatio/ethereum/blockchain.rb:65:in `load_balance_of_address!'\n/home/app/app/services/blockchain_service.rb:20:in `load_balance!'\n/home/app/app/services/wallet_service.rb:81:in `rescue in load_balance!'\n/home/app/app/services/wallet_service.rb:77:in `load_balance!'\n/home/app/app/models/wallet.rb:93:in `current_balance'\n/home/app/app/services/wallet_service.rb:29:in `block in spread_deposit'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/relation/delegation.rb:71:in `each'\n/home/app/app/services/wallet_service.rb:25:in `map'\n/home/app/app/services/wallet_service.rb:25:in `spread_deposit'\n/home/app/app/models/deposit.rb:63:in `spread_between_wallets!'\n/home/app/app/workers/amqp/deposit_collection_fees.rb:24:in `block in process'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/locking/pessimistic.rb:84:in `block in with_lock'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'\n/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:212:in `transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/transactions.rb:301:in `transaction'\n/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/locking/pessimistic.rb:82:in `with_lock'\n/home/app/app/workers/amqp/deposit_collection_fees.rb:16:in `process'\nlib/daemons/amqp_daemon.rb:63:in `block (2 levels) in <main>'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer.rb:56:in `call'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/channel.rb:1768:in `block in handle_frameset'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `loop'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `catch'\n/opt/vendor/bundle/ruby/2.6.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `run_loop'"}
{"level":"ERROR","time":"2020-06-16 21:17:31","message":"Exit..."}

**Comment by alxtrade** [comment]
The issue persists, all ETH deposit collections are skipped. Logs

{"level":"WARN","time":"2020-06-18 23:04:21","message":"The deposit was spreaded in the next way: [{:to_address=>\"0xfaff9beb4ab93a4aa7d95f8e43449302afc987ba\", :amount=>\"0.00986337\", :currency_id=>\"eth\", :status=>\"pending\"}]"}
{"level":"WARN","time":"2020-06-18 23:04:21","message":"Deposit collection job enqueue."}
