### ISSUE TITLE
Generating deposit address error

### ISSUE THREAD

**Issue by shinji12307084** [openware/opendax#175]
I have set the stack (2-4-stable) up with `rake service:all` with only changing the domain and subdomain in `config/app.yml` according to the instructions.

But it seems to me like up to this point, the setup is not complete.

I managed to login with the seeded users:
`Email: admin@barong.io, password: 0lDHd9ufs9t@`

Once I go to the wallet interface, the UI just shows me the message "Generating deposit address" forever. Sometimes "Failed to decode cookies" for version 2.3 of Baseapp.

![Screen Shot 2020-07-03 at 7 18 33 PM](https://user-images.githubusercontent.com/67787288/86465089-817baf00-bd63-11ea-87f9-43c685bc6f1f.png)

I have tried configuring a blockchain node in the Tower according to the instructions in this article

https://medium.com/openware/how-to-configure-blockchain-node-in-the-tower-opendax-5e75e3264e18

but I am getting the same error as addressed by one of the responses of the article

`curl: (6) Could not resolve host: parity`

Then I check the blockchain logs of the Opendax deployment using the command

`docker-compose logs -f blockchain`

```
blockchain_1               | {"level":"WARN","time":"2020-07-03 11:09:27","message":"Error: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known). Sleeping for 10 seconds"}
blockchain_1               | {"level":"ERROR","time":"2020-07-03 11:09:42","message":"#<Peatio::Blockchain::ClientError: Failed to open TCP connection to parity:8545 (getaddrinfo: Name or service not known)>"}
blockchain_1               | {"level":"ERROR","time":"2020-07-03 11:09:42","message":"/home/app/lib/peatio/ethereum/blockchain.rb:60:in `rescue in latest_block_number'\n/home/app/lib/peatio/ethereum/blockchain.r
b:57:in `latest_block_number'\n/home/app/app/services/blockchain_service.rb:16:in `latest_block_number'\n/home/app/app/workers/daemons/blockchain.rb:22:in `process'\n/home/app/app/workers/daemons/blockchain.rb:9
:in `block (3 levels) in run'"}
```

I have tried restarting the blockchain daemon with the command

`docker-compose up -Vd blockchain`

And recheck the logs, same error.

I also tried to bring up the optional cryptonodes component with the command

`rake service:cryptonodes[start]`

Restarted the blochain daemon, check the logs, same error.

---
Apparently the person from the Openware team demonstrating the set up has the same error

https://medium.com/openware/deploy-your-own-crypto-trading-platform-opendax-on-digital-ocean-in-15-minutes-24ca0308fbb3

https://www.youtube.com/watch?v=mhIwkxGZYKk

See around 19:40 of the Youtube video.

So I'm thinking that this must be a default behavior and I might not have done anything wrong, just the setup instruction is not complete.

If this is the case, probably a more comprehensive setup instructions would be useful.

If anyone could point out what I have done wrong, or guide me to completing the whole setup, I can help document it and make a pull request, for anyone in the future that might have the same issue setting up the stack.

**Comment by freakcoderz** [comment]
rake service:cryptonodes[start] will start the parity node locally and begin syncing. If you don't have it setup somewhere and the exchange pointing to it, you won't get an address.

**Comment by Galaxy-Traveler** [comment]
So Parity must be installed

**Comment by Galaxy-Traveler** [comment]
sudo snap install parity
sudo snap install parity-ui

**Comment by Galaxy-Traveler** [comment]
Parity must be installed
sudo snap install parity
sudo snap install parity-ui
cryptonodes.yaml
volumes:
- ../data/parity:/home/parity/.local/share/io.parity.ethereum
to
../data/parity:/home/app/snap/parity/16707/.local/share/io.parity.ethereum

**Comment by alinetskyi** [comment]
> Parity must be installed
> sudo snap install parity
> sudo snap install parity-ui
> cryptonodes.yaml
> volumes:
> 
> * ../data/parity:/home/parity/.local/share/io.parity.ethereum
>   to
>   ../data/parity:/home/app/snap/parity/16707/.local/share/io.parity.ethereum

Apart from setting up parity, you also need to configure blockchain in the admin panel as well as the deposit wallet for that currency

**Comment by lucagrossi** [comment]
Hi all, I'm having the exact same issue. I changed everything according to the above, but it didn't solve anything. Anyone has some more info?

**Comment by freakcoderz** [comment]
Nope, gave up on this.

**Comment by Galaxy-Traveler** [comment]
Let's try it again:
sudo snap install parity///////////////////////////
nano opendax/temples/compose
services:
  parity:
    image: parity/parity:v2.7.2-stable
    restart: always
    command: |
      --chain=kovan
      --mode=active
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
      --no-persistent-txqueue
    volumes:
      - ../data/parity:/home/parity/.local/share/io.parity.ethereum>>>>>>>>>>>>>>>>>>>
    ports:
      - "127.0.0.1:8545:8545"
       to
     services:
  parity:
    image: parity/parity:v2.7.2-stable
    restart: always
    command: |
      --chain=kovan
      --mode=active
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
      --no-persistent-txqueue
    volumes:
      - ../data/parity:/home/app/snap/parity/16707/.local/share/io.parity.ethereum<<<<<<<<<on ubuntu<<<Location where parity was installed
    ports:
      - "127.0.0.1:8545:8545" 
     SAVE
cd opendax
rake service:cryptonodes && \
rake render:config && \
rake service:all && \
rake service:daemons
=============
Ready to sync
docker-compose up parity
Ctrl+c
reboot
rake service:all

**Comment by Galaxy-Traveler** [comment]
For testnet is ok
For mainnet you will need a ssd min 500GB-2TB

Blockchain mainnet min-450GB

**Comment by lucagrossi** [comment]
OK this works indeed..thanks for all your support! My general question for this is: why isn't this somewhere in a manual or is it so obvious for everyone (and only not to me ;))?

**Comment by Galaxy-Traveler** [comment]
There are questions that sometimes can't be answered?????
The community will always help you.

**Comment by lucagrossi** [comment]
Alright thanks again. It seems to working now, although I can't see that my deposits are processed. 
Furthermore I see that the CPU skyrockets and ultimately (after a minute or so) makes my system unstable after starting the cryptonodes. At Digital Ocean I'm not able to have more than 2 VCPU's and 4GB RAM at this moment for some reason.
Do I need the cryptonodes to work before I can see my balance? or can I do this in a different way?

**Comment by Galaxy-Traveler** [comment]
What OS you use?

**Comment by lucagrossi** [comment]
That helped as well. Thanks! I tried to speed up the block fetching with this command: 
parity --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 4096

However the chain started again at 0 (it is faster), but every time I restarts the cryptonodes now, it start back again at 0. Anyway to solve this?
