### ISSUE TITLE
Opendax is not running on local system using www.app.local yet docker-compose shows all the images running

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [openware/opendax#189]
I believe my title is descriptive enough. I tried to module up opendax on my local system using docker but all to not avail. I followed the listed steps and below are the images of what I have done:

**app.yml**
<img width="824" alt="Screenshot 2020-07-14 at 13 07 55" src="https://user-images.githubusercontent.com/15254043/87432894-8c92d280-c5e0-11ea-84e9-e6fda9f9d202.png">

**/etc/hosts**
<img width="505" alt="Screenshot 2020-07-14 at 13 06 01" src="https://user-images.githubusercontent.com/15254043/87433008-b1874580-c5e0-11ea-8450-6a73fc3a78b8.png">

**docker-compose ps**
<img width="898" alt="Screenshot 2020-07-14 at 13 05 16" src="https://user-images.githubusercontent.com/15254043/87433175-ea271f00-c5e0-11ea-9760-19654d078784.png">

**browser response of my local environment** 
<img width="501" alt="Screenshot 2020-07-14 at 13 05 24" src="https://user-images.githubusercontent.com/15254043/87433239-fca15880-c5e0-11ea-8eb6-bcafda75fac6.png">

**What am I doing wrong**? 
I do not know what I have done wrong. The only thing **I do not understand** anyway is the part of the README file that says: `JWT_PUBLIC_KEY=$(cat config/secrets/rsa-key.pub| base64 -w0) rails s -b 0.0.0.0 (base64 -b0 for macOS)` if that is the problem I am having.

**Comment by Galaxy-Traveler** [comment]
Insert in file /etc/hosts

0.0.0.0 www.your domain

**Comment by Galaxy-Traveler** [comment]
https://github.com/openware/opendax/blob/2-3-stable/README.md

**Comment by AfolabiOlaoluwa** [comment]
Probably I'm missing out something here. I want to run this on my local system, and I have attached the image of my /etc/host file. Even with 0.0.0.0 www.my_domain.local, it doesn't work @Galaxy-Traveler

**Comment by Galaxy-Traveler** [comment]
If I understand correctly, try to test your local ip

**Comment by Galaxy-Traveler** [comment]
what system do you use

**Comment by AfolabiOlaoluwa** [comment]
Yes Opendax doesn’t work on the local system. I use a MacBook. MacOS 10.14: Mojave

**Comment by AfolabiOlaoluwa** [comment]
@Galaxy-Traveler here is the log I got when I tail `opendax_peatio_1` image

```
Olaoluwas-MBP-2:opendax tiwa$ docker logs -f opendax_peatio_1
Link /opt/peatio/config/seed/accounts.yml -> /home/app/config/seed/accounts.yml
Link /opt/peatio/config/seed/wallets.yml -> /home/app/config/seed/wallets.yml
Link /opt/peatio/config/seed/blockchains.yml -> /home/app/config/seed/blockchains.yml
Link /opt/peatio/config/seed/markets.yml -> /home/app/config/seed/markets.yml
Link /opt/peatio/config/seed/trading_fees.yml -> /home/app/config/seed/trading_fees.yml
Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml
Link /opt/peatio/config/plugins.yml -> /home/app/config/plugins.yml
[1] Puma starting in cluster mode...
[1] * Version 3.12.4 (ruby 2.6.5-p114), codename: Llamas in Pajamas
[1] * Min threads: 2, max threads: 8
[1] * Environment: production
[1] * Process workers: 4
[1] * Preloading application
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "REDIS_URL". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "URL_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "FORCE_SECURE_CONNECTION". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "LOG_LEVEL". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "JWT_PUBLIC_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "JWT_AUDIENCE". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_DEPOSIT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_WITHDRAW". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "MINIMUM_MEMBER_LEVEL_FOR_TRADING". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_JWT_PRIVATE_KEY". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_JWT_ALGORITHM". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_USERNAME". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "EVENT_API_RABBITMQ_PASSWORD". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "RANGER_HOST". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "RANGER_PORT". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "VAULT_URL". Already set in ENV. (StructuredWarnings::StandardWarning)
/opt/vendor/bundle/ruby/2.6.0/gems/figaro-1.1.1/lib/figaro/application.rb:88:in `key_skipped!': WARNING: Skipping key "VAULT_TOKEN". Already set in ENV. (StructuredWarnings::StandardWarning)
/home/app/lib/peatio/password_generator.rb:14:in `<module:PasswordGenerator>': already initialized constant PasswordGenerator::CHARS (StructuredWarnings::BuiltInWarning)
/home/app/lib/peatio/password_generator.rb:14:in `<module:PasswordGenerator>': previous definition of CHARS was here (StructuredWarnings::BuiltInWarning)
[1] * Listening on tcp://0.0.0.0:8000
[1] ! WARNING: Detected 2 Thread(s) started in app boot:
[1] ! #<Thread:0x00005555c95fee60@/opt/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:38 sleep_forever> - /opt/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `pop'
[1] ! #<Thread:0x00005555ca5b97b0@/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:299 sleep> - /opt/vendor/bundle/ruby/2.6.0/gems/em-synchrony-1.0.6/lib/em-synchrony/kernel.rb:24:in `sleep'
[1] Use Ctrl-C to stop
I, [2020-07-28T12:49:26.418853 #11]  INFO -- : Installing Puma worker loop.
I, [2020-07-28T12:49:26.553870 #18]  INFO -- : Installing Puma worker loop.
I, [2020-07-28T12:49:26.924834 #25]  INFO -- : Installing Puma worker loop.
[1] - Worker 0 (pid: 11) booted, phase: 0
I, [2020-07-28T12:49:27.325697 #27]  INFO -- : Installing Puma worker loop.
[1] - Worker 1 (pid: 18) booted, phase: 0
[1] - Worker 3 (pid: 27) booted, phase: 0
[1] - Worker 2 (pid: 25) booted, phase: 0
[1] ! Terminating timed out worker: 27
[1] ! Terminating timed out worker: 27
[1] ! Out-of-sync worker list, no 27 worker
[1] ! Out-of-sync worker list, no 27 worker
[1] ! Out-of-sync worker list, no 27 worker
[1] ! Out-of-sync worker list, no 27 worker
I, [2020-07-28T12:51:55.709686 #51]  INFO -- : Installing Puma worker loop.
[1] - Worker 3 (pid: 51) booted, phase: 0
[1] ! Terminating timed out worker: 18
I, [2020-07-28T12:55:04.521365 #63]  INFO -- : Installing Puma worker loop.
[1] - Worker 1 (pid: 63) booted, phase: 0
[Scout] [07/28/20 12:55:09 +0000 1bc360bdb1fa (25)] WARN : Error on checkin to https://checkin.scoutapp.com/apps/checkin.scout?key=&name=www.app.local+%28production%29: :connection_failed

```

**Comment by Galaxy-Traveler** [comment]
8GB of RAM (12GB recommended)
4 cores vCPU (6 cores recommended)
300GB disk space (SSD recommended)

**Comment by AfolabiOlaoluwa** [comment]
I understand that @Galaxy-Traveler, but are there no ways I could make do with it in Development environment before I push to Production?
