### ISSUE TITLE
service:setup error

### ISSUE THREAD

**Issue by MrTuNNe** [openware/opendax#228]
Hi, I am trying to start opendax but I have this error at **service:setup**

`SEGV received in ILL handler
rake aborted!
Command failed with status (127): [docker-compose run --rm peatio bash -c "./...]
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/file_utils.rb:57:in `sh'
lib/tasks/service.rake:143:in `block (2 levels) in <top (required)>'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
lib/tasks/service.rake:282:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.6.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.6.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:setup`

Someone who knows why?

**Comment by alinetskyi** [comment]
> Hi, I am trying to start opendax but I have this error at **service:setup**
> 
> `SEGV received in ILL handler rake aborted! Command failed with status (127): [docker-compose run --rm peatio bash -c "./...] /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/file_utils.rb:57:in `sh' lib/tasks/service.rake:143:in `block (2 levels) in <top (required)>'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
> /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke' lib/tasks/service.rake:282:in `start'
> lib/tasks/service.rake:7:in `call' lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
> lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain' /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
> /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run' /home/app/opendax/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.6.5/bin/rake:23:in `load' /usr/local/rvm/gems/ruby-2.6.5/bin/rake:23:in `
> 
> '
> /usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval' /usr/local/rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `'
> Tasks: TOP => service:setup`
> Someone who knows why?

Hi, I'm sorry to hear that you had trouble installing it, you can find an updated video tutorial on how you can install opendax.

https://www.youtube.com/watch?v=qLjl2csyVPw&ab_channel=MobiDAX
