### ISSUE TITLE
Validation failed: Engine must exist

### ISSUE THREAD

**Issue by jorian** [openware/opendax#258]
Running `rake service:all` stops at seeding the db:

```
ActiveRecord::RecordInvalid: Validation failed: Engine must exist
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/validations.rb:52:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `block in save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:315:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/suppressor.rb:48:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.8/lib/scout_apm/instruments/active_record.rb:437:in `save!'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/persistence.rb:53:in `create!'
/home/app/lib/tasks/seed.rake:73:in `block (4 levels) in <main>'
/home/app/lib/tasks/seed.rake:51:in `each'
/home/app/lib/tasks/seed.rake:51:in `block (3 levels) in <main>'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/transactions.rb:212:in `transaction'
/home/app/lib/tasks/seed.rake:48:in `block (2 levels) in <main>'
/home/app/db/seeds.rb:9:in `<main>'
/opt/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `block in load'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:285:in `load'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:554:in `block in load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:672:in `with_inline_jobs'
/opt/vendor/bundle/ruby/2.6.0/gems/railties-5.2.4.3/lib/rails/engine.rb:554:in `load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/opt/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => seed:markets
```
which is this command:

`docker-compose run --rm peatio bash -c "./bin/link_config && bundle exec rake db:seed"`

What am I missing?

**Comment by alinetskyi** [comment]
Hi, some versions might be inconsistent here and that's why you might hit this problem. 

Please consider watching this video for a stable working deployment.

https://www.youtube.com/watch?v=qLjl2csyVPw&ab_channel=MobiDAX

**Comment by jorian** [comment]
Yes, I noticed your video and got it to work with your version, so it's definitely some mismatch somewhere.

I'd still like to know how this happens, because simply following the readme gives this failure.

**Comment by dpatsora** [comment]
Hi @jorian!
This issue has been fixed.

We release recently 2-6-stable Opendax version. 
Check it out! 
We've added some interesting features.

Feel free to reopen the issues if you have any question

Sincerely yours,
Openware Team
