### ISSUE TITLE
Can't create database with Mysql8

### ISSUE THREAD

**Issue by lucagrossi** [openware/opendax#263]
I tried to connect Opendax to an external Mysql8 database, but that resulted in an error (see screenshot) while bringing up the services. It seems like the code isn't compatible with mysql8. I tested this in both 2.5 and 2.6 release because someone in the community said peatio was compatible with mysql 8 since 2.6 release.

![photo_2021-01-14_15-05-49](https://user-images.githubusercontent.com/76164466/104617323-9aa6d600-568b-11eb-8693-30da3259d6c3.jpg)

**Comment by yhjor** [comment]
same error here

**Comment by yhjor** [comment]
```
   -> 0.0228s
== 20200220133250 RevertOrderTimestampPrecision: migrated (0.0560s) ===========

== 20200305140516 MakeUUIDNotNil: migrating ===================================
-- execute("UPDATE orders SET uuid = (UNHEX(REPLACE(UUID(), \"-\",\"\"))) WHERE uuid IS NULL")
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Unknown column '-' in 'field list': UPDATE orders SET uuid = (UNHEX(REPLACE(UUID(), "-",""))) WHERE uuid IS NULL
/opt/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/opt/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/opt/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/opt/vendor/bundle/ruby/2.6.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/opt/vendor/bundle/ruby/2.6.0/gems/scout_apm-2.6.10/lib/scout_apm/instruments/active_record.rb:279:in `log'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:871:in `block in method_missing'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `block in say_with_time'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:840:in `say_with_time'
/opt/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.5/lib/active_record/migration.rb:860:in `method_missing'
```
