### ISSUE TITLE
Instructions do not work at all. Yeild ERROR:1

### ISSUE THREAD

**Issue by Infineca** [openware/opendax#275]
Upon following the instructions letter by letter, I get this error:
`/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:46                                                                                                                               6:in `start'
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>                                                                                                                               '
/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with                                                                                                                               _friendly_errors'
/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => seed:engines
(See full trace by running task with --trace)
ERROR: 1
rake aborted!
Command failed with status (1): [docker-compose run --rm peatio bash -c "./...]
lib/tasks/service.rake:144:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:282:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.6/gems/rake-13.0.1/exe/rake:27:in `<top (required)>                                                                                                                               '
/home/app/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:setup
(See full trace by running task with --trace)
`

The only way to make it work is to follow the MobiDAX tutorial, and their repository is out of date.

**Comment by ahmadidev** [comment]
What command results in these errors?
Because of this error line `docker-compose run --rm peatio bash -c "./...` I think this may be related to invalid state in container volumes.
You can try:
```
rake docker:down
rake docker:clean # This prunes all related volumes and networks. Please be cautious.
rake service:all
```

If it fails again, try to find error logs for `docker-compose run --rm peatio bash -c "./...` command and post them here.
