### ISSUE TITLE
Error: Requested block number is in a range that is not available yet, because the ancient block sync is still in progress

### ISSUE THREAD

**Issue by manolosolalinde** [openware/opendax#308]
Hi, I am getting this errors with `docker-compose logs -f blockchain`:

blockchain_1            | {"level":"WARN","time":"2021-03-28 18:09:16","message":"Error: Requested block number is in a               range that is not available yet, because the ancient block sync is still in progress. (-32000). Sleeping for 10 seconds"              }
blockchain_1            | {"level":"ERROR","time":"2021-03-28 18:09:26","message":"#<Peatio::Blockchain::ClientError: Requested block number is in a range that is not available yet, because the ancient block sync is still in progress. (-32000)>"}
blockchain_1            | {"level":"ERROR","time":"2021-03-28 18:09:26","message":"/home/app/lib/peatio/ethereum/blockchain.rb:59:in `rescue in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain.rb:32:in `fetch_block!'\n/home/app/app/services/blockchain_service.rb:47:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:38:in `block (3 levels) in start'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.4/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:36:in `block (2 levels) in start'\n/home/app/app/workers/daemons/blockchain.rb:22:in `loop'\n/home/app/app/workers/daemons/blockchain.rb:22:in `block in start'"}

Wallets are working for some users but not for all. Ancients blocks are not syncing:
```bash
curl --data '{"method":"eth_syncing","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":false,"id":1}
```
```bash
curl --data '{"method":"parity_chainStatus","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
{"jsonrpc":"2.0","result":{"blockGap":["0x1","0x1269228"]},"id":1}
```

My `cryptonodes.yml` file looks like this:
```yml
version: '3.6'

services:
  parity:
    image: parity/parity:v2.7.2-stable
    user: "${UID}:${GID}"
    restart: always
    command: |
      --chain=kovan
      --mode=active
      --db-path=/home/app/mydb
      --interface=all
      --warp=true
      --snapshot-peers=10
      --min-peers=5
      --max-peers=10
      --jsonrpc-interface=0.0.0.0
      --jsonrpc-cors=all
      --jsonrpc-hosts=all
      --jsonrpc-apis=all
      --db-compaction=ssd
      --no-persistent-txqueue
    volumes:
      - ../data/parity:/home/app/mydb
      # - ../data/parity:/home/parity/.local/share/io.parity.ethereum
    ports:
      - "127.0.0.1:8545:8545"
```
Any ideas?

**Comment by zeus-dev** [comment]
its stucking please upgrade to openethereum 3.2.5
