### ISSUE TITLE
rake service:all error

### ISSUE THREAD

**Issue by HugoPhoenix** [openware/opendax#336]
To enable version updates, set updateVersions to true
Rendering ./config/applogic/management_api_v2.yml
Rendering ./config/applogic/schedule.yml
Rendering ./config/peatio/seed/accounts.yml
Rendering ./config/peatio/seed/blockchains.yml
Rendering ./config/peatio/seed/currencies.yml
Rendering ./config/peatio/seed/markets.yml
Rendering ./config/peatio/seed/engines.yml
Rendering ./config/peatio/seed/trading_fees.yml
Rendering ./config/peatio/seed/wallets.yml
Rendering ./config/peatio/abilities.yml
Rendering ./config/peatio/management_api_v1.yml
Rendering ./config/frontend/tower.js
Rendering ./config/frontend/env.js
Rendering ./config/gateway/envoy.yaml
Rendering ./config/rango.env
Rendering ./config/vault/peatio_crypto.hcl
Rendering ./config/vault/peatio_rails.hcl
Rendering ./config/vault/barong.hcl
Rendering ./config/vault/peatio_upstream.hcl
Rendering ./config/vault/peatio_matching.hcl
Rendering ./config/vault/finex_engine.hcl
Rendering ./config/barong/seeds.yml
Rendering ./config/barong/abilities.yml
Rendering ./config/barong/management_api.yml
Rendering ./config/toolbox.yaml
Rendering ./config/arke/strategies.yml
Rendering ./config/arke.env
Rendering ./config/mailer.yml
Rendering ./config/litecoin.conf
Rendering ./config/barong.env
Rendering ./config/applogic.env
Rendering ./config/peatio.env
Rendering ./config/bitcoin.conf
Rendering ./config/finex/config.yaml
Rendering ./config/finex/rsa-key.pub
Rendering ./config/mysql/innodb.cnf
Rendering ./terraform/terraform.tfvars
Rendering ./compose/monitoring.yaml
Rendering ./compose/arke.yaml
Rendering ./compose/proxy.yaml
Rendering ./compose/app.yaml
Rendering ./compose/backend.yaml
Rendering ./compose/vendor.yaml
Rendering ./compose/daemons.yaml
Rendering ./compose/cryptonodes.yaml
Rendering ./compose/gateway.yaml
Rendering ./compose/superset.yaml
Rendering ./compose/frontend.yaml
Rendering ./.env
----- Starting the proxy -----
docker-compose up -d proxy
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[8944] Failed to execute script docker-compose
rake aborted!
Command failed with status (255): [docker-compose up -d proxy...]
lib/tasks/service.rake:25:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:33:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:277:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:302:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.6/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/app/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:proxy
(See full trace by running task with --trace)

**Comment by reubenr0d** [comment]
Setting the domain and subdomain in the `config/app.yml` seemed to resolve the 404 error for me.

**Comment by ahmadidev** [comment]
404 means the server (Traefik) is up and running but the domain you're requesting is not found. Make sure the domain name specified in `/etc/hosts` and `config/app.yml` are the same. And please note that if you change `config/app.yml` you need to run subsequent commands:
```
rake render:config
rake service:all
```

**Comment by gianghungtien** [comment]
> 

Solved
