### ISSUE TITLE
BSC blockchain convert_from_base_unit fetch  problem peatio:3.0.13

### ISSUE THREAD

**Issue by rubi022** [openware/opendax#395]
{"level":"WARN","time":"2023-01-19 21:02:35","message":"Error: undefined method `fetch' for nil:NilClass. Sleeping for 10 seconds"}
{"level":"ERROR","time":"2023-01-19 21:02:46","message":"#<NoMethodError: undefined method `fetch' for nil:NilClass>"}
{"level":"ERROR","time":"2023-01-19 21:02:46","message":"/home/app/lib/peatio/ethereum/blockchain_abstract.rb:278:in `convert_from_base_unit'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:197:in `build_eth_transactions'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:189:in `build_transactions'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:96:in `block in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `each'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `each_with_object'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `fetch_block!'\n/home/app/app/services/blockchain_service.rb:49:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:38:in `block (3 levels) in start'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:36:in `block (2 levels) in start'\n/home/app/app/workers/daemons/blockchain.rb:22:in `loop'\n/home/app/app/workers/daemons/blockchain.rb:22:in `block in start'"}
{"level":"WARN","time":"2023-01-19 21:02:46","message":"Error: undefined method `fetch' for nil:NilClass. Sleeping for 10 seconds"}

BSC syncs at first and I try to reset the block height to latest one then I get error

**Comment by mameex** [comment]
same

blockchain_1               | {"level":"ERROR","time":"2023-09-13 12:06:11","message":"/home/app/lib/peatio/ethereum/blockchain_abstract.rb:278:in `convert_from_base_unit'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:197:in `build_eth_transactions'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:189:in `build_transactions'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:96:in `block in fetch_block!'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `each'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `each_with_object'\n/home/app/lib/peatio/ethereum/blockchain_abstract.rb:53:in `fetch_block!'\n/home/app/app/services/blockchain_service.rb:49:in `process_block'\n/home/app/app/workers/daemons/blockchain.rb:38:in `block (3 levels) in start'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/opt/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.4.5/lib/active_support/core_ext/range/each.rb:9:in `each'\n/home/app/app/workers/daemons/blockchain.rb:36:in `block (2 levels) in start'\n/home/app/app/workers/daemons/blockchain.rb:22:in `loop'\n/home/app/app/workers/daemons/blockchain.rb:22:in `block in start'"}
