### ISSUE TITLE
Can't build per instructions

### ISSUE THREAD

**Issue by gulfpearl** [openware/opendax#67]
I've followed the instructions and at the `bundle install` stage it aborts with the following:

```
  current directory: /home/app/.rvm/gems/ruby-2.6.3/gems/puma-3.12.2/ext/puma_http11
/home/app/.rvm/rubies/ruby-2.6.3/bin/ruby -I /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0 -r
./siteconf20191227-20873-sq82em.rb extconf.rb
checking for BIO_read() in -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/app/.rvm/rubies/ruby-2.6.3/bin/$(RUBY_BASE_NAME)
        --with-puma_http11-dir
        --without-puma_http11-dir
        --with-puma_http11-include
        --without-puma_http11-include=${puma_http11-dir}/include
        --with-puma_http11-lib
        --without-puma_http11-lib=${puma_http11-dir}/lib
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-cryptolib
        --without-cryptolib
/home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable
file. (RuntimeError)
You have to install development tools first.
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:1016:in `block in have_library'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/mkmf.rb:1011:in `have_library'
        from extconf.rb:8:in `block in <main>'
        from extconf.rb:8:in `each'
        from extconf.rb:8:in `find'
        from extconf.rb:8:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/app/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/puma-3.12.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/app/.rvm/gems/ruby-2.6.3/gems/puma-3.12.2 for inspection.
Results logged to /home/app/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/puma-3.12.2/gem_make.out

An error occurred while installing puma (3.12.2), and Bundler cannot continue.
Make sure that `gem install puma -v '3.12.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  puma
```

**Comment by gulfpearl** [comment]
The only thing I did different than the instructions was the following, because it wouldn't work without giving user `app` sudo powers:

```
rvm autolibs disable
rvm requirements
```

**Comment by gulfpearl** [comment]
I got past that problem, I had to do:

` apt install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm5 libgdbm-dev
`
and reinstall ruby as the app user. This should be added to the instructions.

**Comment by Guillerbr** [comment]
Follow the installation instructions and everything installs correctly.

**Comment by alinetskyi** [comment]
@Guillerbr @gulfpearl 

There is an updated video instruction on how you can install opendax and it's available right here:

https://www.youtube.com/watch?v=qLjl2csyVPw&ab_channel=MobiDAX
