### ISSUE TITLE
Services don't start

### ISSUE THREAD

**Issue by gulfpearl** [openware/opendax#68]
After installing everything per instructions, when I try to start the services, I get the following error:

> [docker-compose up -d proxy
> rake aborted!
> Command failed with status (127): [docker-compose up -d proxy...]]

Here is the full message:

```
app@gearex:~/opendax/config$ rake service:all start --trace
(in /home/app/opendax)
** Invoke service:all (first_time)
** Invoke render:config (first_time)
** Execute render:config
Rendering ./compose/components-docs.yaml
Rendering ./compose/proxy.yaml
Rendering ./compose/vendor.yaml
Rendering ./compose/daemons.yaml
Rendering ./compose/frontend.yaml
Rendering ./compose/backend.yaml
Rendering ./compose/app.yaml
Rendering ./compose/superset.yaml
Rendering ./compose/arke.yaml
Rendering ./compose/cryptonodes.yaml
Rendering ./compose/gateway.yaml
Rendering ./config/toolbox.yaml
Rendering ./config/arke/strategies.yml
Rendering ./config/arke/etl.yml
Rendering ./config/gateway/envoy.yaml
Rendering ./config/traefik.toml
Rendering ./config/arke.env
Rendering ./config/peatio.env
Rendering ./config/frontend/env.js
Rendering ./config/frontend/tower.js
Rendering ./config/postmaster.env
Rendering ./config/peatio/seed/accounts.yml
Rendering ./config/peatio/seed/markets.yml
Rendering ./config/peatio/seed/blockchains.yml
Rendering ./config/peatio/seed/currencies.yml
Rendering ./config/peatio/seed/trading_fees.yml
Rendering ./config/peatio/seed/wallets.yml
Rendering ./config/peatio/management_api_v1.yml
Rendering ./config/applogic.env
Rendering ./config/barong.env
Rendering ./config/mysql/innodb.cnf
Rendering ./config/applogic/management_api_v2.yml
Rendering ./config/applogic/schedule.yml
Rendering ./config/postmaster.yml
Rendering ./config/ranger.env
Rendering ./config/barong/management_api.yml
Rendering ./.env
Rendering ./terraform/terraform.tfvars
** Execute service:all
** Invoke service:proxy (first_time)
** Execute service:proxy
----- Starting the proxy -----
docker-compose up -d proxy
rake aborted!
Command failed with status (127): [docker-compose up -d proxy...]
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/file_utils.rb:57:in `sh'
lib/tasks/service.rake:25:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:33:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
lib/tasks/service.rake:267:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:294:in `block (2 levels) in <top (required)>'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/app/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/home/app/.rvm/gems/ruby-2.6.3/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/app/.rvm/gems/ruby-2.6.3/bin/rake:23:in `load'
/home/app/.rvm/gems/ruby-2.6.3/bin/rake:23:in `<main>'
/home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/app/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => service:proxy
```

**Comment by Guillerbr** [comment]
rake service: all

**Comment by dpatsora** [comment]
Hi @gulfpearl !
Thanks for reaching out.

Seems that you didn't install docker-compose on your machine. Please, check [this](https://github.com/openware/opendax#22-install-docker-and-docker-compose) section of our README.

Sincerely yours,
OW team
