### ISSUE TITLE
Errno::EACCES: Permission denied @ rb_sysopen - config/secrets/barong.key

### ISSUE THREAD

**Issue by k7n2g** [openware/opendax#86]
says it all really

using Debian 9.x
added google bucket and its Access keys for the user account bundle okay but gives this error and cant rake service:all 

Errno::EACCES: Permission denied @ rb_sysopen - config/secrets/barong.key
/home/app/opendax/lib/opendax/renderer.rb:62:in `initialize'
/home/app/opendax/lib/opendax/renderer.rb:62:in `open'
/home/app/opendax/lib/opendax/renderer.rb:62:in `generate_key'
/home/app/opendax/lib/opendax/renderer.rb:54:in `render_keys'
lib/tasks/render.rake:8:in `block (2 levels) in <top (required)>'
Tasks: TOP => service:all => render:config

what have i failed to do or got wrong please any help appreciated

**Comment by k7n2g** [comment]
sorted this issue only to bring up other issue when running install.sh.

rake aborted!
Command failed with status (1): [docker-compose up -d frontend...]
lib/tasks/service.rake:184:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:192:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:275:in `start'
lib/tasks/service.rake:7:in `call'

any ideas on this guys  have tried a few things but not working.
