### ISSUE TITLE
Google 2FA

### ISSUE THREAD

**Issue by GerardoTaboada** [openware/opendax#92]
Hello! How do I enable Google 2fa? I get 500 error. Thank you

**Comment by k7n2g** [comment]
only user can enable 2fa  just did this on my phone, downloaded google authenticate as  exchange user took code pic on screen logs in perfectly

**Comment by GerardoTaboada** [comment]
Yes of course, I said on the server side that I can not activate it to then use the app, do I have to use any api?

**Comment by alinetskyi** [comment]
> Yes of course, I said on the server side that I can not activate it to then use the app, do I have to use any api?

Hi, looks like you have a problem with vault. 

Can you please try to do the following and paste the output

`docker-compose exec vault`
`vault status`

**Comment by m4hdi1995** [comment]
same issue

**Comment by alinetskyi** [comment]
@m4hdi1995 Can you provide the output of the command I've requested. 
Also, please consider joining our community group. We provide a lot of support there
https://t.me/mobiDAX_group

**Comment by m4hdi1995** [comment]
@alinetskyi i think that was a vault problem as you mentioned, i stopped all services, then i started vault and unsealed it then i started all of the services and problem solved.

**Comment by alinetskyi** [comment]
@m4hdi1995 Great! 
Happy to hear it helped. Hope this helps others too !

**Comment by ggbbest** [comment]
i have same isue
 {"error":"Route is not found"} 

/ # vault status
Key             Value
---             -----
Seal Type       shamir
Sealed          false
Total Shares    1
Threshold       1
Version         0.10.2
Cluster Name    vault-cluster-c65db4d6
Cluster ID      21c513a9-9af9-620c-20ce-c1cf658b49b0
HA Enabled      false
/ # 


The Vault server at `http://vault:8200' responded with a 404.\nAny additional information the server supplied is shown below:\n\n  * no handler for route 'totp/keys/ID7475E550E6'\n\nPlease refer to the documentation for help.\n\n/home/app/vendor/bundle/ruby/2.6.0/gems/vault-0.12.0/lib/vault/client.rb:400:in `error'\n/home/app/vendor/bundle/ruby/2.6.0/gems/vault-0.12.0/lib/vault/client.rb:291:in `request'\n/home/app/vendor/bundle/ruby/2.6.0/gems/vault-0.12.0/lib/vault/client.rb:203:in `put'\n/home/app/vendor/bundle/ruby/2.6.0/gems/vault-0.12.0/lib/vault/api/logical.rb:68:in `write'\n/home/app/app/services/totp_service.rb:79:in `block in write_data'\n/home/app/app/services/totp_service.rb:47:in `with_human_error
